name: Keep Streamlit Cloud App Alive

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://indicator-dashboard-dyp7oscj3twv9stxdb5zbn.streamlit.app/
          echo "Pinged app at $(date)"